// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace verificateur.Models;

public partial class CBFil
{
    public string IdArticle { get; set; }

    public string IdFils { get; set; } = null!;

    public virtual Article IdArticleNavigation { get; set; }
}