// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace verificateur.Models;

public partial class dbVerificateurContext : DbContext
{
    public dbVerificateurContext(DbContextOptions<dbVerificateurContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Article> Articles { get; set; }

    public virtual DbSet<CBFil> CBFils { get; set; }

    public virtual DbSet<Famille> Familles { get; set; }

    public virtual DbSet<Marque> Marques { get; set; }

    public virtual DbSet<Station> Stations { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Article>(entity =>
        {
            entity.HasKey(e => e.IdArticle);

            entity.ToTable("Article");

            entity.Property(e => e.IdArticle).HasMaxLength(30);
            entity.Property(e => e.DDPromotion).HasColumnType("datetime");
            entity.Property(e => e.DFPromotion).HasColumnType("datetime");
            entity.Property(e => e.DesignationArticle).HasMaxLength(150);
            entity.Property(e => e.IdFamille).HasMaxLength(30);
            entity.Property(e => e.IdMarque).HasMaxLength(30);
            entity.Property(e => e.IdStation).HasMaxLength(30);
            entity.Property(e => e.ImageArt).HasColumnType("image");
            entity.Property(e => e.PrixPromotion).HasColumnType("decimal(18, 3)");
            entity.Property(e => e.PrixTTC).HasColumnType("decimal(18, 3)");
            entity.Property(e => e.TauxPromotion).HasColumnType("decimal(18, 3)");

            entity.HasOne(d => d.IdFamilleNavigation).WithMany(p => p.Articles)
                .HasForeignKey(d => d.IdFamille)
                .HasConstraintName("FK_Article_Famille");

            entity.HasOne(d => d.IdMarqueNavigation).WithMany(p => p.Articles)
                .HasForeignKey(d => d.IdMarque)
                .HasConstraintName("FK_Article_Marque");

            entity.HasOne(d => d.IdStationNavigation).WithMany(p => p.Articles)
                .HasForeignKey(d => d.IdStation)
                .HasConstraintName("FK_Article_Station");
        });

        modelBuilder.Entity<CBFil>(entity =>
        {
            entity.HasKey(e => e.IdFils);

            entity.Property(e => e.IdFils).HasMaxLength(30);
            entity.Property(e => e.IdArticle)
                .IsRequired()
                .HasMaxLength(30);

            entity.HasOne(d => d.IdArticleNavigation).WithMany(p => p.CBFils)
                .HasForeignKey(d => d.IdArticle)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CBFils_Article");
        });

        modelBuilder.Entity<Famille>(entity =>
        {
            entity.HasKey(e => e.IdFamille);

            entity.ToTable("Famille");

            entity.Property(e => e.IdFamille).HasMaxLength(30);
            entity.Property(e => e.DesignationFamille).HasMaxLength(150);
        });

        modelBuilder.Entity<Marque>(entity =>
        {
            entity.HasKey(e => e.IdMarque);

            entity.ToTable("Marque");

            entity.Property(e => e.IdMarque).HasMaxLength(30);
            entity.Property(e => e.DesignationMarque).HasMaxLength(150);
        });

        modelBuilder.Entity<Station>(entity =>
        {
            entity.HasKey(e => e.IdStation);

            entity.ToTable("Station");

            entity.Property(e => e.IdStation).HasMaxLength(30);
            entity.Property(e => e.Adresse).HasMaxLength(30);
            entity.Property(e => e.Designation).HasMaxLength(150);
            entity.Property(e => e.logo).HasColumnType("image");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}