// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace verificateur.Models;

public partial class Famille
{
    public string IdFamille { get; set; } 

    public string? DesignationFamille { get; set; }

    public virtual ICollection<Article> Articles { get; set; } = new List<Article>();
}