// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace verificateur.Models;

public partial class Marque
{
    public string IdMarque { get; set; } = null!;

    public string? DesignationMarque { get; set; }

    public virtual ICollection<Article> Articles { get; set; } = new List<Article>();
}