// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace verificateur.Models;

public partial class Station
{
    public string? IdStation { get; set; } = null!;

    public string? Adresse { get; set; }

    public byte[]? logo { get; set; }

    public string? Designation { get; set; }

    public virtual ICollection<Article> Articles { get; set; } = new List<Article>();
}